# `try` Blocks and Exception Handling

## Exercises

5.23. Write a program that reads two integers from the standard input and
prints the result of dividing the first number by the second.
([source](./ex_5_23.cpp))

5.24. Revise your program to throw an exception if the second number is zero.
Test your program with zero input to see what happens on your system if you
don't `catch` an exeption. ([source](./ex_5_24.cpp))

5.25. Revise your program from the previous exercise to use a `try` block to
`catch` the exeption. The `catch` clause should print a message to the user
and ask them to supply a new number and repeat the code inside the `try`.
([source](./ex_5_25.cpp))
